spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.168.22.48/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId:  wx7bd9355a6a6345a8 #公众号appId
  mpAppSecret: 78641dca3fd57c2a799c65a818c7a7ed  #公众号appSeceret
  mchId:  #商户号ID
  mchKey: #商户号KEY
  KeyPath: #证书存放地址
  notifyUrl: http://16106642.ngrok.io/sell/pay/notify #异步回调地址

#支付宝支付所需参数
alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appId: 2016082000296143
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCzwHd9RY5e3OgqqX+7WorPoN2Fc65hyMTUQ/eukXrbG+IBYzzhpvQC/F5lmyzymwcxnICpRgNE5R85QvRFUXv7BNvpvUGHE1rDolMjk3Ysx12APRvUEjSQipuLOVsBi2kOXF0kH9nw32oIRCd30HI6v7uhmNBaSDW4XzjRQidLz/VQG4Ndx50J54xvKYzhPyVkARj0wU3PVA7VtfgJ/5nGT0CxU6Wk9burtPufTRNhjyfRqXopiw1Klaod7sO+G8lsOQw8zse6nGlRA2QVZtI/qC0AW38knNEEW68e/XO0nlm5ScYy5TuP2S4W2BAcawnqjNlGalXE9l/7jFOSASilAgMBAAECggEAc4TvxdxbwO9rbW99HWT07LbPZqKPoVwr0tbTaKcqM4JZ3tZuG/71tq2F5PqzCj9Dgki4DxFlrHMre9thrOLPMOVQh4kPgcWYgT3i/GwaeHCv0Gh1Z/dDPNk3WWRE7lsv6wDFAyBNKhYKyME0NDYME2GBLjtNO5hInfLkSuee5YLtLDpybvkug9orjCUW6GTh/IVRhR3ZBZgtZj4Ptztl6SeemKy5HKPbF8JpA/60/RDqei7xNbKCetw6xFvNyNtmbl2y9TsVNGSwnhN/BwIVqn7mBWQOHb/1b5b7uMYgUGiRgpaHVWRQRMspYBPf93nD8vt2cuUYpywjB6gSdagYCQKBgQDu5DUj3E7CkooY5RAoi/jd8JWf8B5D/mi5Hu6j6ueJ9qBWFz+FWsT3cvFMRhOylxrvRXjFuLTH3uFyIDS59GtoLwURW87nvLhOAe9TQNR/SgaKYLKRfeyvwMduEEB1nYIlu7U0U0UXlKQmz5Pzk0y7qSpLMH5lej4mR5R6SBTpBwKBgQDAoAETlLSqZNWrOcQujoH9GCFLascz2yXJ3XacYgg3EqSlVVa4QoawYox3WqLNzEcsHf8ozBWE+lFRMAau16Y+7FahLxROnhNXCliJHTYEWmqA0K+UsT0+19KrO3yRz4dDqkj1PWOwcNwH7WMDN8tRZjv/pdfVt23HYt3bnL2R8wKBgCKSC86gtxUZN7raizgS6XTUuBJpITgdvPHtNAOsns0sT4+l1Z9qv04/6ANtsLQLge5WU1/plt/FtUJavsaaRGDTTRxx+MM4YEOJrCSUISw6fi/QRocfff0BHNskpu9eV9M2Esb7tefvrsGfEH4TNuuBU4mF/wSYaB4KBcacX8pJAoGAB5VE9ZRhGGQn1TnM81hA3cnZZbKqbOwvrKa/SKDDWget26RkaZSU4NTAWuKCjj+Afcggh2ahYj7IfL27RZ7PuKJtNqM31XB7qm2J1rwDqGA22SNeBiiEFLlCXeNVoBffZ1aI0L698fA/eUBrKXFE28t+iS3qNUunUrYdrcuZ2ukCgYA/vD1wx21M54iXlneEXndRQKSSbONMZssQ6OKp7VuEuVA1Smsx4hmuEE1LGJ5rj8JmZiSiG3HnEN9DqnRh8K4h2SAuWm1qWGEghkdhoL/dGn31uAXcvhOKobHLa/v7aYrNYn2ao7pANNFenmYiwLCx3bU7cq7lqaIOgmUSxw5YDw==
  format: json
  charset: UTF-8
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx/H8al7PRkW5FpRmkIm7fNE2bS2SGebIOrPur2QgicK4V9u1pCmAXQkhtzKcTdxDCZMOPwK0XVXvIhMBdWJabR+Urz2FYV13AsnS7Aqg5TbwcwMGbkO3p/a1kHKIkkPejYeOmVGiOmpZsC/hi7Jc9naJB9WdnbZ2hS7zYI6Zn1JhhsSVPyjxjsqgwMCbOahB1EJ30S+mFBtTnJTabgcLA1lG8NanQGgTFBPGG9JsBEXcsBqAn63X0ar/6bP639GbrkBxv8fBzAwFNSv3lvGj9c5U82l0joDovFH5YqV9uijszOoMfX1a+e02kcXPXI/XtenUs2rfhXR4H7FrdtmgEQIDAQAB
  signType: RSA2
  # 当面付最大查询次数和查询间隔（毫秒）
  maxQueryRetry: 5
  queryDuration: 5000