spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.105/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId:  wx7bd9355a6a6345a8 #公众号appId
  mpAppSecret: 78641dca3fd57c2a799c65a818c7a7ed  #公众号appSeceret
  mchId:  #商户号ID
  mchKey: #商户号KEY
  KeyPath: #证书存放地址
  notifyUrl: #异步回调地址